### ISSUE TITLE
Logout does not work!

### ISSUE THREAD

**Issue by mjza** [isopropylcyanide/Jwt-Spring-Security-JPA#12]
When I try to logout, it will show a SUCCESS message for logout. 

> {
>     "data": "Log out successful",
>     "success": true,
>     "timestamp": "2020-07-06T07:55:10.948Z"
> }

However still the old token is usable and I can access to data via `/user/me` with the old token!

**Comment by isopropylcyanide** [comment]
Hi @mjza the token will stay valid for the duration until it expires. In a real enterprise grade application, the client layer deletes the token from their local storage (browser cache, cookie) post the success of the logout API. The expectation is that the token will not be reused again. 

A Client layer can also delete the token after a certain period of inactivity (effective logout). Facebook might log you out after 3 months (refresh token timeout). 

Your use case of saying that `/user/me` works is because you have access to the token. This should not be available in a real app. Depending on the security of the app, you set a smaller expiration time in the token and have clients refresh it after a certain period. 

**A JWT token is immutable, self signed and has all the information within it. It cannot be changed.**
You have an alternative though.

- What you can do is write the tokens off to a KV store (like Redis or in-memory if security is less critical and read QPS is high) once the logout API succeeds. Call it the `logged-out-token-store`

- Before accepting any requests, you quickly lookup on the store to see if a token is a logged out token or not. If it is, you delete it. This requires fast lookups. Hence the closer the lookup server is to the application server, the better.

- Once this store is built, you can write a batch offline job that polls your store and removes the JWT tokens that are past their expiry as it doesn't make sense to store all logged out tokens if they are already expired. This will help keep your key count in check.

The above concept, is outside the scope of this project, however trivial.

**Comment by mjza** [comment]
It is interesting that you say the access to the resources  can be provided by having the token even after a successful logout. 
The problem is somebody can take this token and use it until the expiration time. 
I believe the token must be somehow invalidate after the logout. 
Otherwise why do I have to tell the back-end that the user has logged out?
I tell back-end user has logged out that the token could not be used for accessing the system any more!

I am going to use your code beside an odata server. 
It is very good and clean, however still I believe we have to somehow invalidate the jwt token in the back-end (something like what you suggested).

If you can provide an implementation for that I would be appreciated.

**Comment by isopropylcyanide** [comment]
- Logout is by design, achieved here through a stateless mechanism. When you carry no state, there are always trade offs. Hence, if you lose or compromise your token (using it even after a server logout), all is lost.  You can read about what happens when you lose a token [here](https://developer.okta.com/blog/2018/06/20/what-happens-if-your-jwt-is-stolen#what-happens-if-your-json-web-token-is-stolen) 

- I'm sure the invalidation of a JWT token would be a solved problem (through external means only). You can look around for implementations online. Although I think I can provide a trivial implementation here. Will take some time out today and try to code it up.

- Thank you for your comment on the codebase being clean.

**Comment by isopropylcyanide** [comment]
@mjza You can take a pull from master now. The check for token invalidation has been added.

**Comment by mjza** [comment]
@isopropylcyanide Thanks a lot. I will check it soon.

**Comment by mjza** [comment]
Dear @isopropylcyanide, I tested the app. It works perfect. Thanks.
